#!/bin/sh
#/etc/init.d/MagicMirror
export PATH=$PATH:/home/pi/MagicMirror
export NODE_PATH=$NODE_PATH:/home/pi/MagicMirror/node_modules

case "$1" in
start)
exec forever start --sourceDir=/home/pi/MagicMirror -p /home/pi/MagicMirror indexServer.js  #scriptarguments
;;
stop)
exec forever stop --sourceDir=/home/pi/MagicMirror indexServer.js
;;
*)
echo "Usage: /etc/init.d/MagicMirror {start|stop}"


exit 1
;;
esac
exit 0
